/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FuelType = IDL.Variant({
  'petrol' : IDL.Null,
  'diesel' : IDL.Null,
});
export const Time = IDL.Int;
export const Prebooking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'fuelType' : FuelType,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
  'contactNumber' : IDL.Text,
  'requiredDeliveryDate' : Time,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
  'wallet' : IDL.Null,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'branch' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'employee' : IDL.Principal,
  'fuelType' : FuelType,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
});
export const FuelStockLevel = IDL.Record({
  'petrol' : IDL.Float64,
  'diesel' : IDL.Float64,
});
export const Branch = IDL.Record({
  'id' : IDL.Text,
  'dieselPrice' : IDL.Float64,
  'lowStockThreshold' : IDL.Float64,
  'name' : IDL.Text,
  'petrolStock' : IDL.Float64,
  'dieselStock' : IDL.Float64,
  'petrolPrice' : IDL.Float64,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'branch' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const LoyaltyMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'totalPoints' : IDL.Nat,
  'phone' : IDL.Text,
});
export const LoyaltyPointTransaction = IDL.Record({
  'id' : IDL.Nat,
  'saleId' : IDL.Opt(IDL.Nat),
  'employee' : IDL.Principal,
  'timestamp' : Time,
  'points' : IDL.Nat,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoyaltyPoints' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBranch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createPrebooking' : IDL.Func(
      [IDL.Text, IDL.Text, FuelType, IDL.Float64, Time],
      [IDL.Nat],
      [],
    ),
  'getBranchBookings' : IDL.Func([IDL.Text], [IDL.Vec(Prebooking)], ['query']),
  'getBranchSales' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
  'getBranchStockLevels' : IDL.Func([IDL.Text], [FuelStockLevel], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getLoyaltyMembers' : IDL.Func([], [IDL.Vec(LoyaltyMember)], ['query']),
  'getLoyaltyPointTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LoyaltyPointTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSale' : IDL.Func(
      [IDL.Text, FuelType, IDL.Float64, PaymentMethod],
      [IDL.Nat],
      [],
    ),
  'registerLoyaltyMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBranchStock' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'updateFuelPrices' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'updatePrebookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FuelType = IDL.Variant({ 'petrol' : IDL.Null, 'diesel' : IDL.Null });
  const Time = IDL.Int;
  const Prebooking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'fuelType' : FuelType,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
    'contactNumber' : IDL.Text,
    'requiredDeliveryDate' : Time,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'wallet' : IDL.Null,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'branch' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'employee' : IDL.Principal,
    'fuelType' : FuelType,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
  });
  const FuelStockLevel = IDL.Record({
    'petrol' : IDL.Float64,
    'diesel' : IDL.Float64,
  });
  const Branch = IDL.Record({
    'id' : IDL.Text,
    'dieselPrice' : IDL.Float64,
    'lowStockThreshold' : IDL.Float64,
    'name' : IDL.Text,
    'petrolStock' : IDL.Float64,
    'dieselStock' : IDL.Float64,
    'petrolPrice' : IDL.Float64,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'branch' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const LoyaltyMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'totalPoints' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const LoyaltyPointTransaction = IDL.Record({
    'id' : IDL.Nat,
    'saleId' : IDL.Opt(IDL.Nat),
    'employee' : IDL.Principal,
    'timestamp' : Time,
    'points' : IDL.Nat,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoyaltyPoints' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBranch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createPrebooking' : IDL.Func(
        [IDL.Text, IDL.Text, FuelType, IDL.Float64, Time],
        [IDL.Nat],
        [],
      ),
    'getBranchBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prebooking)],
        ['query'],
      ),
    'getBranchSales' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
    'getBranchStockLevels' : IDL.Func([IDL.Text], [FuelStockLevel], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getLoyaltyMembers' : IDL.Func([], [IDL.Vec(LoyaltyMember)], ['query']),
    'getLoyaltyPointTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LoyaltyPointTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSale' : IDL.Func(
        [IDL.Text, FuelType, IDL.Float64, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'registerLoyaltyMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBranchStock' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateFuelPrices' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
    'updatePrebookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };