/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branch {
  'id' : string,
  'dieselPrice' : number,
  'lowStockThreshold' : number,
  'name' : string,
  'petrolStock' : number,
  'dieselStock' : number,
  'petrolPrice' : number,
  'location' : string,
}
export interface Employee {
  'id' : string,
  'branch' : string,
  'name' : string,
  'role' : string,
}
export interface FuelStockLevel { 'petrol' : number, 'diesel' : number }
export type FuelType = { 'petrol' : null } |
  { 'diesel' : null };
export interface LoyaltyMember {
  'id' : string,
  'name' : string,
  'totalPoints' : bigint,
  'phone' : string,
}
export interface LoyaltyPointTransaction {
  'id' : bigint,
  'saleId' : [] | [bigint],
  'employee' : Principal,
  'timestamp' : Time,
  'points' : bigint,
  'reason' : string,
}
export type PaymentMethod = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null } |
  { 'wallet' : null };
export interface Prebooking {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'fuelType' : FuelType,
  'timestamp' : Time,
  'quantity' : number,
  'contactNumber' : string,
  'requiredDeliveryDate' : Time,
}
export interface Sale {
  'id' : bigint,
  'branch' : string,
  'paymentMethod' : PaymentMethod,
  'employee' : Principal,
  'fuelType' : FuelType,
  'totalAmount' : number,
  'timestamp' : Time,
  'quantity' : number,
}
export type Time = bigint;
export interface UserProfile {
  'branch' : [] | [string],
  'name' : string,
  'employeeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoyaltyPoints' : ActorMethod<
    [string, bigint, string, [] | [bigint]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBranch' : ActorMethod<[string, string, string], undefined>,
  'createEmployee' : ActorMethod<[string, string, string, string], undefined>,
  'createPrebooking' : ActorMethod<
    [string, string, FuelType, number, Time],
    bigint
  >,
  'getBranchBookings' : ActorMethod<[string], Array<Prebooking>>,
  'getBranchSales' : ActorMethod<[string], Array<Sale>>,
  'getBranchStockLevels' : ActorMethod<[string], FuelStockLevel>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getLoyaltyMembers' : ActorMethod<[], Array<LoyaltyMember>>,
  'getLoyaltyPointTransactions' : ActorMethod<
    [string],
    Array<LoyaltyPointTransaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSale' : ActorMethod<[string, FuelType, number, PaymentMethod], bigint>,
  'registerLoyaltyMember' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBranchStock' : ActorMethod<[string, number, number], undefined>,
  'updateFuelPrices' : ActorMethod<[string, number, number], undefined>,
  'updatePrebookingStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];